# Generated by Django 4.0 on 2022-01-28 10:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('financial_year', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Grants',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=27700)),
                ('grant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='peatdash.grant')),
            ],
            options={
                'verbose_name_plural': 'Sites',
            },
        ),
        migrations.CreateModel(
            name='RestorationPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique', models.CharField(choices=[('peat_dam', 'Peat dam'), ('gully_block', 'Gully block'), ('stone_dam', 'Stone dam'), ('wooden_dam', 'Wooden dam')], max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=27700)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='peatdash.site')),
            ],
            options={
                'verbose_name_plural': 'Restoration points',
            },
        ),
        migrations.CreateModel(
            name='RestorationLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique', models.CharField(choices=[('peat_dam', 'Peat dam'), ('hag_reprofling', 'Hag reprofiling'), ('gully_reprofiling', 'Gully reprofiling'), ('wave_dam', 'Wave dam')], max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=27700)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='peatdash.site')),
            ],
            options={
                'verbose_name_plural': 'Restoration lines',
            },
        ),
    ]
