# Generated by Django 4.0 on 2022-01-24 22:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrantReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_id', models.CharField(max_length=6)),
                ('name', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('financial_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteOutline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('grant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peatdash.grantreference')),
            ],
        ),
        migrations.CreateModel(
            name='RestorationPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique', models.IntegerField(choices=[(1, 'Peat dam'), (2, 'Gully block')])),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peatdash.siteoutline')),
            ],
        ),
        migrations.CreateModel(
            name='RestorationLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique', models.IntegerField(choices=[(1, 'Peat dam'), (2, 'Hag reprofiling')])),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peatdash.siteoutline')),
            ],
        ),
    ]
