# Generated by Django 4.0 on 2022-02-02 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('peatdash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='auth.user'),
            preserve_default=False,
        ),
    ]
