# Generated by Django 4.0 on 2022-01-24 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peatdash', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restorationlines',
            options={'verbose_name_plural': 'Restoration lines'},
        ),
        migrations.AlterModelOptions(
            name='restorationpoints',
            options={'verbose_name_plural': 'Restoration points'},
        ),
        migrations.AlterModelOptions(
            name='siteoutline',
            options={'verbose_name_plural': 'Site outlines'},
        ),
    ]
